# Generated by Django 2.1.2 on 2018-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_write_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='write_up',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
