# Generated by Django 2.1.2 on 2018-11-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181119_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='spotify',
            field=models.CharField(default='', max_length=200),
        ),
    ]
