# Generated by Django 2.1.2 on 2018-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_spotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='spotify',
            field=models.CharField(default="Add 'embed' between '...com/' and '/track...'", max_length=200),
        ),
    ]
