# Generated by Django 2.1.2 on 2018-11-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20181120_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='map',
            field=models.CharField(default='Just add URL', max_length=5000),
        ),
    ]
