# Generated by Django 2.1.2 on 2018-11-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='map',
        ),
    ]
